name: tryondiffusion
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310h4e76f89_0
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2023.08.22=hecd8cb5_0
  - cffi=1.15.1=py310h6c40b1e_3
  - gmp=6.2.1=he9d5cce_3
  - gmpy2=2.1.2=py310hd5de756_0
  - intel-openmp=2023.1.0=ha357a0b_43547
  - jinja2=3.1.2=py310hecd8cb5_0
  - libcxx=14.0.6=h9765a3e_0
  - libffi=3.4.4=hecd8cb5_0
  - libprotobuf=3.20.3=hfff2838_0
  - libuv=1.44.2=h6c40b1e_0
  - mkl=2023.1.0=h8e150cf_43559
  - mkl-service=2.4.0=py310h6c40b1e_1
  - mkl_fft=1.3.8=py310h6c40b1e_0
  - mkl_random=1.2.4=py310ha357a0b_0
  - mpc=1.1.0=h6ef4df4_1
  - mpfr=4.0.2=h9066e36_1
  - mpmath=1.3.0=py310hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - networkx=3.1=py310hecd8cb5_0
  - ninja=1.10.2=hecd8cb5_5
  - ninja-base=1.10.2=haf03e11_5
  - numexpr=2.8.7=py310h827a554_0
  - openssl=3.0.11=hca72f7f_2
  - pandas=2.1.1=py310h3ea8b11_0
  - pip=23.2.1=py310hecd8cb5_0
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.10.13=h5ee71fb_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2023.3.post1=py310hecd8cb5_0
  - readline=8.2=hca72f7f_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h6c40b1e_0
  - tbb=2021.8.0=ha357a0b_0
  - tk=8.6.12=h5d9f67b_0
  - tzdata=2023c=h04d1e81_0
  - wheel=0.38.4=py310hecd8cb5_0
  - xz=5.4.2=h6c40b1e_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
    - absl-py==2.0.0
    - aiofiles==23.2.1
    - annotated-types==0.6.0
    - anyio==4.3.0
    - appnope==0.1.3
    - asttokens==2.4.0
    - astunparse==1.6.3
    - backcall==0.2.0
    - cachetools==5.3.1
    - carvekit==4.1.1
    - certifi==2023.7.22
    - charset-normalizer==3.2.0
    - click==8.1.7
    - comm==0.1.4
    - contourpy==1.1.1
    - cycler==0.11.0
    - debugpy==1.8.0
    - decorator==5.1.1
    - diffusers==0.29.2
    - einops==0.7.0
    - exceptiongroup==1.1.3
    - executing==1.2.0
    - fastapi==0.108.0
    - ffmpy==0.3.3
    - filelock==3.12.4
    - flatbuffers==23.5.26
    - fonttools==4.42.1
    - fsspec==2024.3.1
    - gast==0.5.4
    - google-auth==2.23.3
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - gradio==4.39.0
    - gradio-client==1.1.1
    - gradio-modal==0.0.3
    - grpcio==1.59.0
    - h11==0.14.0
    - h5py==3.10.0
    - httpcore==1.0.5
    - httpx==0.27.0
    - huggingface-hub==0.23.4
    - idna==3.4
    - imageio==2.34.0
    - importlib-metadata==8.0.0
    - importlib-resources==6.4.0
    - ipykernel==6.25.2
    - ipython==8.15.0
    - jedi==0.19.0
    - jupyter-client==8.3.1
    - jupyter-core==5.3.1
    - keras==2.14.0
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - libclang==16.0.6
    - loguru==0.7.2
    - markdown==3.5
    - markdown-it-py==3.0.0
    - markupsafe==2.1.3
    - matplotlib==3.8.0
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - ml-dtypes==0.2.0
    - nest-asyncio==1.5.8
    - numpy==1.26.4
    - oauthlib==3.2.2
    - opencv-python==4.8.1.78
    - opt-einsum==3.3.0
    - orjson==3.10.6
    - packaging==23.1
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==10.1.0
    - platformdirs==3.10.0
    - prompt-toolkit==3.0.39
    - protobuf==4.24.4
    - psutil==5.9.5
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pydantic==2.5.3
    - pydantic-core==2.14.6
    - pydub==0.25.1
    - pygments==2.16.1
    - pyparsing==3.1.1
    - python-dotenv==1.0.1
    - python-multipart==0.0.9
    - pyyaml==6.0.1
    - pyzmq==25.1.1
    - regex==2024.5.15
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rich==13.7.1
    - rsa==4.9
    - ruff==0.5.5
    - safetensors==0.4.3
    - scikit-image==0.22.0
    - scipy==1.11.4
    - semantic-version==2.10.0
    - setuptools==69.0.3
    - shellingham==1.5.4
    - sniffio==1.3.1
    - stack-data==0.6.2
    - starlette==0.32.0.post1
    - sympy==1.12
    - tensorboard==2.14.1
    - tensorboard-data-server==0.7.1
    - tensorflow==2.14.0
    - tensorflow-estimator==2.14.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.3.0
    - tifffile==2024.2.12
    - tokenizers==0.19.1
    - tomlkit==0.12.0
    - torch==2.1.2
    - torchvision==0.16.2
    - tornado==6.3.3
    - tqdm==4.66.1
    - traitlets==5.10.0
    - transformers==4.42.4
    - typer==0.12.3
    - typing==3.7.4.3
    - typing-extensions==4.8.0
    - urllib3==2.0.5
    - uvicorn==0.25.0
    - wcwidth==0.2.6
    - websockets==11.0.3
    - werkzeug==3.0.0
    - wrapt==1.14.1
    - zipp==3.19.2
prefix: /Users/apple/miniconda3/envs/tryondiffusion
